telegram.bot.username=Username8209_bot
telegram.bot.token=8993560253:AAF15-CMRfEvsqjYjusShVTTwl0zZl-PVyA
ai.proxy.url=https://shaitest-production-3066.up.railway.app/api-request
ai.proxy.token=3rugqeuljJtZj31MShOhJ6J7lnRPu0i28skmPnu5kfxtDC3I0AtFaIv2Ek8f3blu